version: '3'
services:
   web:
      container_name: Mapbox-API-flask
      hostname: Mapbox-API-flask
      build: .
      ports:
         - '5000:5000'
    
   db:
      image: postgres:12-alpine
      volumes:
         - data-db:/var/lib/postgresql/data
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=password123
         - POSTGRES_DB=coordenadas_api
      ports:
         - "5432:5432"
      restart: always

volumes:
   data-db: